###
POST http://127.0.0.1:8000/run-pnet/
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="config_file"; filename="config.toml"

< test/fmri_surf_hcp10subjs.toml
--WebAppBoundary
Content-Disposition: form-data; name="file_Brain_Template"; filename="template.nii"
#
